{"tag": "function", "depth": 1, "time": 1610355585.95803, "data": {"name": "shell", "call_args": {"cmd": "am force-stop com.kugou.shiqutouch"}, "start_time": 1610355585.344657, "ret": "", "end_time": 1610355585.95803}}
{"tag": "function", "depth": 1, "time": 1610355587.0250583, "data": {"name": "start_app", "call_args": {"package": "com.kugou.shiqutouch", "activity": null}, "start_time": 1610355585.95803, "ret": null, "end_time": 1610355587.0250583}}
{"tag": "function", "depth": 1, "time": 1610355592.0258765, "data": {"name": "sleep", "call_args": {"secs": 5}, "start_time": 1610355587.0250583, "ret": null, "end_time": 1610355592.0258765}}
{"tag": "info", "depth": 0, "time": 1610355598.3621147, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\poco\\proxy.py\", line 26, in wrapped\n    proxy.wait_for_appearance(timeout=proxy.poco._pre_action_wait_for_appearance)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\poco\\proxy.py\", line 681, in wait_for_appearance\n    raise PocoTargetTimeout('appearance', self)\npoco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of \"UIObjectProxy of \"com.kugou.shiqutouch:id/ids_pager_shiqu_online_extract\"\"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\airtest\\cli\\runner.py\", line 61, in runTest\n    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), self.scope)\n  File \"D:\\CC\\program\\cx_test_tool\\Folder\\APP_xn_auto_folder\\air\\ShiPinTiQu.air\\ShiPinTiQu.py\", line 29, in <module>\n    poco(\"com.kugou.shiqutouch:id/ids_pager_shiqu_online_extract\").click()\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\poco\\proxy.py\", line 29, in wrapped\n    raise e\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\poco\\proxy.py\", line 23, in wrapped\n    return func(proxy, *args, **kwargs)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\poco\\proxy.py\", line 332, in click\n    pos_in_percentage = self.get_position(focus)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\poco\\proxy.py\", line 72, in wrapped\n    return func(proxy, *args, **kwargs)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\poco\\proxy.py\", line 613, in get_position\n    pos = self.attr('pos')\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\poco\\proxy.py\", line 39, in wrapped\n    return func(self, *args, **kwargs)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\poco\\proxy.py\", line 734, in attr\n    nodes = self._do_query(multiple=False)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\poco\\proxy.py\", line 874, in _do_query\n    raise PocoNoSuchNodeException(self)\npoco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of \"com.kugou.shiqutouch:id/ids_pager_shiqu_online_extract\"\n"}}
